### PR TITLE
Version bump for openssl update

### PR DESCRIPTION
**Pull request by koala-kalda**

### CODE REVIEW

**Comment by koala-kalda** [comment]
#45

**Comment by Gisleburt** [comment]
I'm being pedantic, but this should probably be a patch, no features have been added 😉

**Comment by koala-kalda** [comment]
True that - my bad.

**Comment by koala-kalda** [comment]
And fixed accordingly :)

**Comment by pickfire** [comment]
@GildedHonour Any update on this?

**Comment by GildedHonour** [comment]
No 

El 14 de noviembre de 2018 11:40:49 GMT-05:00, Ivan Tham <notifications@github.com> escribió:
>@GildedHonour Any update on this?
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/GildedHonour/frank_jwt/pull/46#issuecomment-438730199

-- 
Enviado desde mi dispositivo Android con K-9 Mail. Por favor, disculpa mi brevedad.

**Comment by richerarc** [comment]
Will this be merge anytime soon?

**Comment by GildedHonour** [comment]
I plan to do an update myself soon, this merge may not be needed.

Within around a week.

**Comment by koala-kalda** [comment]
Is there any reason to delay? A simple merge and push to crates.io would fix problems for a lot of your users.

**Comment by GildedHonour** [comment]
new version has been published

**Pull request closed without merging**
