### PR TITLE
Add test documentation

### LINKED ISSUE #30: Documentation example didn't compile
Compiler didn't like the first example given on https://crates.io/crates/frank_jwt. References and values on parameters seemed to be mixed up. Here's what works for me (with unwrap ready for serialisation):

```
let payload = json!({
    "key1" : "val1",
    "key2" : "val2"
});
let header = json!({});
let secret = "secret123";
let jwt = encode(header, &secret.to_string(), &payload, Algorithm::HS256).unwrap();
```

### PR DESCRIPTION
**Pull request by apiraino**
Fixes #30 

Besides fixing the README file, I thought to also add some documentation as tests, so they'll appear in docs.rs - let's make 2019 the year of well documented libraries in Rust :^)

I did run `rustfmt` (automatically run-on-save on my setup) over the code and committed some linting aside, up to you to cherry pick or merge everything.

Opinions @GildedHonour ?

Thanks for evaluating this patch! :+1:

### CODE REVIEW

**Comment by GildedHonour** [comment]
"r" what?

**Comment by apiraino** [comment]
Sorry, `r` as in "review".

I am confused on why the PR was rejected without comments. Just wondering why, whether it needs more work, or maybe it doesn't fit a work-in-progress already started elsewhere, etc.

(just curious)

**Comment by GildedHonour** [comment]
There were the comments

**Comment by apiraino** [comment]
@GildedHonour Sorry, I'm not sure I'm following you.

Anyway, no problem. Thanks anyways.

**Comment by GildedHonour** [comment]
captura de pantalla 2019-01-19 a la s 23 37 57

**Comment by apiraino** [comment]
That's really weird, I didnt receive *any* comments for this PR, and I don't see any comments right now :thinking: 

When you have some spare time, would you mind adding these comments again?

(sorry for the extra work)

**Comment by Terkwood** [comment]
Totally weird. I can't see it either. Bad Github, bad!

**Comment by GildedHonour** [comment]
I think it was me who didn't submit a review.

**Pull request closed without merging**
