### PR TITLE
Accept tokens and keys as &str

### PR DESCRIPTION
**Pull request by felipenoris**

### CODE REVIEW

**Comment by GildedHonour** [comment]
How is having `impl<'a> ToKey for &'a str` better than calling `to_string()`?

**Comment by felipenoris** [comment]
How is it worse?
With this you can use string slices as input without additional allocations turning them into a string before vec. It is also a syntax sugar. And it doesn't break existing code, just adds a new possibility.

**Comment by GildedHonour** [comment]
And it also adds more code. 


El 7 de octubre de 2018 20:33:00 GMT-05:00, Felipe Noronha <notifications@github.com> escribió:
>How is it worse?
>With this you can use string slices as input without additional
>allocations turning them into a string before vec. It is also a syntax
>sugar. And it doesn't break existing code, just adds a new possibility.
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/GildedHonour/frank_jwt/pull/42#issuecomment-427704208

-- 
Enviado desde mi dispositivo Android con K-9 Mail. Por favor, disculpa mi brevedad.

**Comment by felipenoris** [comment]
Feel free to reject this PR.

**Comment by tilacog** [comment]
I believe this PR makes a lot of sense.

> How is having `impl<'a> ToKey for &'a str` better than calling `to_string()`?

IMHO using `&str` instead of `&String` for argument types is more ergonomic and memory efficient as the end user does not need to allocate memory for the intermediary `String`. It also makes life easier when using `static` and `const` values as inputs.

References:
- [String vs &str in Rust functions](https://hermanradtke.com/2015/05/03/string-vs-str-in-rust-functions.html)

**Comment by GildedHonour** [comment]
@tilacog the PR doesn't allow to avoid allocation.

**Comment by felipenoris** [comment]
How come? It allows one less allocation.

Before

```rust
let x = "str";
let s = x.to_string(); // allocation here
let v = s.as_bytes().to_vec(); // allocation here
```

With `&str` you get one less allocation:

```rust
let x = "str";
let v = x.as_bytes().to_vec(); // allocation here
```

**Comment by GildedHonour** [comment]
In the PR allocation would still happen in the trait.

El 8 de octubre de 2018 8:52:58 GMT-05:00, Felipe Noronha <notifications@github.com> escribió:
>How come? It allows one less allocation.
>
>Before
>
>```rust
>let x = "str";
>let s = x.to_string(); // allocation here
>let v = s.as_bytes().to_vec(); // allocation here
>```
>
>With `&str` you get one less allocation:
>
>```rust
>let x = "str";
>let v = x.as_bytes().to_vec(); // allocation here
>```
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/GildedHonour/frank_jwt/pull/42#issuecomment-427842209

-- 
Enviado desde mi dispositivo Android con K-9 Mail. Por favor, disculpa mi brevedad.

**Comment by felipenoris** [comment]
Really? Can you point that out to us?

**Comment by GildedHonour** [comment]
You're right, it doesn't

**Comment by GildedHonour** [comment]
> Even if this was not the case for less allocations, I don't understand why it is bad to allow for an easier to use API at the cost of 4 additional lines of code, just because it adds more code.

Those who need &str, are able to convert String to &str themselfs by calling .string(), on their side. This is not difficult. 

And there're also those who don't need &str.

**Comment by brunoczim** [comment]
I would like to add some points to this discussion. 

First of all, if you have a &String, you cannot do anything different than if you have a &str. The whole point of needing String is to change the size of the allocation (generally via pushes). &String cannot change the size of the allocation because it is immutable. So there is no benefit requiring &String instead of &str.

However, producing a &str is much easier than producing &String. &str may come from a static string literal, from slicing from some variable whose source is unknown, etc. It may also come from a String too! And all of these are zero cost. Requiring a &String is not zero cost and it disable the programmer from doing things like producing a subslice with zero cost. 

Also, remember String coerces to str, and even if it doesn't, calling methods like .as_ref(), .borrow() or derreferencing &**s is zero cost.

Requiring &String is a very odd pattern in Rust.

**Comment by GildedHonour** [comment]
That's not 2 cents. It's at least $2.4. If not more. :)

How much more RAM does that one additional allocation cost you?

**Comment by brunoczim** [comment]
Allocation costs are not only about RAM but about speed as well. There is some CPU overhead with heap allocation. If you execute this code on a loop or "many times" it may become a bottleneck.

**Comment by brunoczim** [comment]
Also, even though it seems a small extra space, it is not justification for this waste of memory. Lots of small extra space are a big extra space.

**Comment by GildedHonour** [comment]
>If you execute this code on a loop or "many times" it may become a bottleneck.

Or may not. Prove that.

> Also, even though it seems a small extra space, it is not justification for this waste of memory. 

Yes, it is.

**Comment by brunoczim** [comment]
Bro, you are author of an open source project. Be more reasonable and receptive, please.

**Comment by saks** [comment]
JFYI guys: I've migrated to [jsonwebtoken](https://github.com/Keats/jsonwebtoken) and pretty happy with it. It's API does not force you to allocate `String` without a good reason.

**Pull request closed without merging**
