### PR TITLE
Refactor function &String parameters to &str

### PR DESCRIPTION
**Pull request by mandreyel**
It's a more idiomatic way to pass string references to functions. Hope this is welcome. Thanks!

### CODE REVIEW

**Comment by mandreyel** [comment]
Also added a `ToKet` trait implementation for `&str`. Would be nicer to just do this:
```rust
impl<T> ToKey for T
where
    T: AsRef<[u8]>
{
    fn to_key(&self) -> Result<Vec<u8>, Error> {
        self.as_ref().to_bytes()
    }
}
```
But alas that would conflict with the `PathBuf` trait impl that has a differing implementation.

**Comment by GildedHonour** [comment]
@mandreyel 

Maybe. On the other hand, the more code, more complexity.

**Comment by mandreyel** [comment]
@GildedHonour Do you mean my comment with the generic `ToKey` implementation? That's not included in the PR and I think the PR itself is not complex at all.

**Comment by Terkwood** [comment]
Thanks!

**Pull request merged**
